### PR TITLE
Change exit() instances to throw exceptions

### LINKED ISSUE #136: Change `exit()` instances to throw exceptions.
Currently, we `exit()` in various places in chimera where we encounter unexpected states.  Instead, in #135 @mkoval suggested we switch to throwing exceptions in those places.

### PR DESCRIPTION
**Pull request by jslee02**
Fixes #136

### CODE REVIEW

File: src/configuration.cpp [hunk 1]
```diff
@@ -408,7 +400,7 @@ chimera::CompiledConfiguration::CompiledConfiguration(
         = [](const std::string &str) -> std::string { return str; };
 }
 
-chimera::CompiledConfiguration::~CompiledConfiguration()
+chimera::CompiledConfiguration::~CompiledConfiguration() noexcept(false)
```
Comment (psigen) [inline src/configuration.cpp:403]: It is a bit weird to be doing this in the destructor.  I wonder if there is a different location in the visitor call chain where this would make more sense :thinking:

**Comment by jslee02** [comment]
All sounds good. One issue would be that `Visitor` takes `std::unique_ptr<CompiledConfiguration>` so we have to move the created unique_ptr to the constructor of `Visitor` and then cannot access to the compiled config.

Possible solutions would be:
1. change the constructor of `Visitor` to take `shared_ptr<CompiledConfiguration>`
1. add a method to `Visitor` to return a raw pointer to the compiled config
Which one would be good for this case?

**Comment by jslee02** [comment]
Merging as the comment is resolved by #269
